export const CONFIG = {
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
  SOCKET_URL: process.env.NEXT_PUBLIC_SOCKET_URL!,
  DEFAULT_SERVER_IMAGE_URL: process.env.NEXT_PUBLIC_DEFAULT_SERVER_IMAGE_URL!,
};
